
version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tracking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog.xml
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_ENABLED: "true"

volumes:
  pgdata:
